version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=smartinventory;Username=postgres;Password=postgres
    volumes:
      - ./src:/app/src
    ports:
      - "5000:8080"
