// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInventory.Infrastructure.Data;

#nullable disable

namespace SmartInventory.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518204145_AddAssetPhotoPath")]
    partial class AddAssetPhotoPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartInventory.Domain.Asset.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartInventory.Domain.Asset.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentRoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetectedRoomCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastDetectedUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MaintenanceDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("RfidTagId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("RfidTagId")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssetTag = "AST-LI-001",
                            Category = "Computer",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5430),
                            CurrentRoomCode = "LI1",
                            InstallDate = new DateTime(2025, 11, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5449),
                            LastServiceDate = new DateTime(2026, 4, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5461),
                            MaintenanceDueDate = new DateTime(2026, 7, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5462),
                            Manufacturer = "Dell",
                            Model = "XPS 15 9530",
                            Name = "Dell Laptop XPS 15",
                            SerialNumber = "DL-XPS-001",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssetTag = "AST-LI-002",
                            Category = "Display",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5469),
                            CurrentRoomCode = "LI2",
                            InstallDate = new DateTime(2026, 1, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5474),
                            Manufacturer = "HP",
                            Model = "P24h",
                            Name = "HP Monitor 24inch",
                            SerialNumber = "HP-MON-002",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssetTag = "AST-LI-003",
                            Category = "Printer/Scanner",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5480),
                            CurrentRoomCode = "LI3",
                            InstallDate = new DateTime(2025, 9, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5485),
                            LastServiceDate = new DateTime(2026, 3, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5486),
                            MaintenanceDueDate = new DateTime(2026, 6, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5487),
                            Manufacturer = "Canon",
                            Model = "MF644CDW",
                            Name = "Canon Printer MF644",
                            SerialNumber = "CN-PRT-003",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AssetTag = "AST-LI-004",
                            Category = "Projector",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5493),
                            CurrentRoomCode = "LI4",
                            InstallDate = new DateTime(2025, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5495),
                            Manufacturer = "Epson",
                            Model = "EB-2250U",
                            Name = "Epson Projector",
                            SerialNumber = "EP-PRJ-004",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AssetTag = "AST-MEC-001",
                            Category = "Computer",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5529),
                            CurrentRoomCode = "MEC1",
                            InstallDate = new DateTime(2026, 2, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5532),
                            LastServiceDate = new DateTime(2026, 5, 4, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5533),
                            Manufacturer = "Dell",
                            Model = "Inspiron 15",
                            Name = "Dell Laptop Inspiron",
                            SerialNumber = "DL-INS-005",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AssetTag = "AST-MEC-002",
                            Category = "Display",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5551),
                            CurrentRoomCode = "MEC2",
                            InstallDate = new DateTime(2025, 12, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5554),
                            Manufacturer = "Samsung",
                            Model = "S27F350",
                            Name = "Samsung Monitor 27inch",
                            SerialNumber = "SM-MON-006",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AssetTag = "AST-GEST-001",
                            Category = "Printer/Scanner",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5560),
                            CurrentRoomCode = "GEST1",
                            InstallDate = new DateTime(2025, 7, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5562),
                            LastServiceDate = new DateTime(2026, 4, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5563),
                            MaintenanceDueDate = new DateTime(2026, 8, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5564),
                            Manufacturer = "HP",
                            Model = "LaserJet Pro M404n",
                            Name = "HP Printer LaserJet",
                            SerialNumber = "HP-PRT-007",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AssetTag = "AST-0000003",
                            Category = "Printer/Scanner",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5570),
                            CurrentRoomCode = "LI1",
                            Description = "Imprimante laser couleur - 30 ppm",
                            DetectedRoomCode = "LI1",
                            InstallDate = new DateTime(2026, 3, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5572),
                            MaintenanceDueDate = new DateTime(2026, 9, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5573),
                            Manufacturer = "HP",
                            Model = "LaserJet Pro M404n",
                            Name = "Imprimante HP LaserJet Pro",
                            SerialNumber = "HP-LJ-003",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AssetTag = "AST-INV-001",
                            Category = "Display",
                            CreatedAt = new DateTime(2026, 5, 18, 20, 41, 44, 502, DateTimeKind.Utc).AddTicks(5579),
                            CurrentRoomCode = "STOCK",
                            Description = "Nouveau moniteur en stock, pas encore déployé",
                            Manufacturer = "Dell",
                            Model = "E2222H",
                            Name = "Dell Monitor 22inch",
                            SerialNumber = "DL-MON-INV-001",
                            Status = 5
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Asset.Entities.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("PropertyChanged")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("SmartInventory.Domain.Asset.Entities.CategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("CategoryGroups", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Auth.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SmartInventory.Domain.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.AssetLocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewRoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousRoomCode")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssetLocationHistories");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "Code")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.RoomGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stroke")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomGeometries", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Mobile.Auth.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Mobile.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Mobile.Entities.SyncQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOperationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetRoomCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOperationId")
                        .IsUnique();

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("DeviceId", "IsProcessed");

                    b.ToTable("SyncQueueEntries", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Notification.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartInventory.Domain.UserPreferences.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("SmartInventory.Domain.Asset.Entities.AssetHistory", b =>
                {
                    b.HasOne("SmartInventory.Domain.Asset.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("SmartInventory.Domain.Auth.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("SmartInventory.Domain.Auth.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Building", b =>
                {
                    b.HasOne("SmartInventory.Domain.Location.Entities.Zone", "Zone")
                        .WithMany("Buildings")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Floor", b =>
                {
                    b.HasOne("SmartInventory.Domain.Location.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Room", b =>
                {
                    b.HasOne("SmartInventory.Domain.Location.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.RoomGeometry", b =>
                {
                    b.HasOne("SmartInventory.Domain.Location.Entities.Room", "Room")
                        .WithOne("RoomGeometry")
                        .HasForeignKey("SmartInventory.Domain.Location.Entities.RoomGeometry", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Zone", b =>
                {
                    b.HasOne("SmartInventory.Domain.Location.Entities.Site", "Site")
                        .WithMany("Zones")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SmartInventory.Domain.Mobile.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartInventory.Domain.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInventory.Domain.UserPreferences.Entities.UserPreference", b =>
                {
                    b.HasOne("SmartInventory.Domain.Auth.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInventory.Domain.Auth.Entities.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Room", b =>
                {
                    b.Navigation("RoomGeometry");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Site", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SmartInventory.Domain.Location.Entities.Zone", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
